import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';

/**
 * GET: Fetches the full conversation thread for a lead — combining:
 *   1. Sent emails from the lead's emailHistory (what we sent)
 *   2. Incoming emails (what the lead replied)
 *   3. AI responses for each incoming email (what we generated/sent back)
 *
 * Query params:
 *   leadEmail — the lead's email address
 *   leadId    — alternatively, the lead's ID
 *
 * Returns a chronological list of messages with type: 'sent' | 'received' | 'ai_response'
 */
export async function GET(request: NextRequest): Promise<NextResponse> {
  try {
    const { searchParams } = new URL(request.url);
    const leadEmail = searchParams.get('leadEmail') || '';
    const leadId = searchParams.get('leadId') || '';

    if (!leadEmail && !leadId) {
      return NextResponse.json({
        success: false,
        error: 'Either leadEmail or leadId is required'
      }, { status: 400 });
    }

    // Find the lead
    const lead = await prisma.lead.findFirst({
      where: leadId
        ? { id: leadId }
        : { email: { equals: leadEmail, mode: 'insensitive' } },
      select: {
        id: true,
        email: true,
        name: true,
        company: true,
        status: true,
        emailHistory: true,
      }
    });

    if (!lead) {
      return NextResponse.json({
        success: false,
        error: 'Lead not found'
      }, { status: 404 });
    }

    // 1. Build sent emails from emailHistory
    const emailHistory = (lead.emailHistory as any[]) || [];
    const sentEmails = emailHistory
      .filter((entry: any) => entry?.status === 'sent' && entry?.sentAt)
      .map((entry: any) => {
        const content = entry?.emailContent || {};
        return {
          id: `sent-${entry.messageId || entry.trackingId || entry.sentAt}`,
          type: 'sent' as const,
          subject: content?.subject || entry?.subject || '',
          content: content?.textContent || content?.text || '',
          htmlContent: content?.htmlContent || '',
          fromAddress: content?.from || '',
          toAddress: content?.to || lead.email,
          stage: entry?.stage || '',
          sentAt: entry.sentAt,
          messageId: entry?.messageId || '',
          trackingId: entry?.trackingId || '',
        };
      })
      .sort((a, b) => new Date(a.sentAt).getTime() - new Date(b.sentAt).getTime());

    // 2. Fetch incoming emails with their AI responses
    const incomingEmails = await prisma.incomingEmail.findMany({
      where: {
        leadEmail: {
          equals: lead.email,
          mode: 'insensitive'
        }
      },
      include: {
        aiResponses: {
          orderBy: { createdAt: 'asc' }
        }
      },
      orderBy: { receivedAt: 'asc' }
    });

    // 3. Build received emails + AI responses
    const receivedEmails: any[] = [];
    for (const incoming of incomingEmails) {
      const meta = (incoming.metadata as any) || {};
      receivedEmails.push({
        id: incoming.id,
        type: 'received' as const,
        subject: incoming.subject,
        content: incoming.content,
        htmlContent: incoming.htmlContent || '',
        fromAddress: meta.fromAddress || incoming.leadEmail,
        toAddress: meta.toAddress || '',
        receivedAt: incoming.receivedAt.toISOString(),
        isReply: incoming.isReply,
        conversationCount: incoming.conversationCount,
        isThirdReply: incoming.isThirdReply,
        status: incoming.status,
        metadata: incoming.metadata,
      });

      // Add AI responses for this incoming email
      for (const ai of incoming.aiResponses) {
        receivedEmails.push({
          id: ai.id,
          type: 'ai_response' as const,
          subject: ai.generatedSubject,
          content: ai.generatedContent,
          htmlContent: ai.generatedContent,
          fromAddress: '',
          toAddress: lead.email,
          status: ai.status,
          responseType: ai.responseType,
          reasoning: ai.reasoning,
          sentAt: ai.sentAt?.toISOString() || ai.createdAt.toISOString(),
          autoGenerated: ai.autoGenerated,
        });
      }
    }

    // 4. Merge and sort chronologically
    const allMessages = [...sentEmails, ...receivedEmails]
      .map(msg => ({
        ...msg,
        _timestamp: new Date(
          (msg as any).sentAt || (msg as any).receivedAt || (msg as any).createdAt
        ).getTime()
      }))
      .sort((a, b) => a._timestamp - b._timestamp)
      .map(({ _timestamp, ...rest }) => rest);

    return NextResponse.json({
      success: true,
      lead: {
        id: lead.id,
        email: lead.email,
        name: lead.name,
        company: lead.company,
        status: lead.status,
      },
      thread: allMessages,
      count: allMessages.length,
      summary: {
        sent: sentEmails.length,
        received: incomingEmails.length,
        aiResponses: incomingEmails.reduce((sum, e) => sum + e.aiResponses.length, 0),
      }
    });

  } catch (error: any) {
    console.error('❌ Error fetching conversation thread:', error);
    return NextResponse.json({
      success: false,
      error: error.message || 'Failed to fetch conversation thread'
    }, { status: 500 });
  }
}
