"use client";

import { useState, useEffect } from "react";
import { SectionHeader } from "@/components/ui/section-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { 
  Mail, 
  Send, 
  RefreshCw, 
  Bot, 
  MessageSquare, 
  Clock, 
  CheckCircle, 
  AlertTriangle,
  Eye,
  Edit,
  Sparkles,
  Building,
  ArrowRight,
  Copy,
  Save,
  Trash2
} from "lucide-react";
import { toast } from "sonner";
import { useEmailResponseTranslations } from "@/hooks/use-email-response-translations";
import { auth } from "@/lib/auth";
import { Switch } from "@/components/ui/switch";
import { cn } from "@/lib/utils";

// Type definitions
interface CombinedEmailData {
  email: {
    id: string;
    leadId: string;
    leadName: string;
    leadEmail: string;
    leadCompany: string;
    subject: string;
    content: string;
    htmlContent?: string;
    receivedAt: string;
    status: 'unread' | 'pending_ai' | 'responded';
    sentiment: string;
    isReply: boolean;
    conversationCount: number;
    isThirdReply: boolean;
    metadata?: any;
  };
  originalSentEmail: {
    subject: string;
    content: string;
    htmlContent: string;
    fromAddress: string;
    sentAt: string;
    stage: string;
  } | null;
  totalSentEmails: number;
  aiResponse: {
    id: string;
    generatedSubject: string;
    generatedContent: string;
    status: 'draft' | 'sent' | 'failed';
    reasoning: string;
    responseType: string;
    createdAt: string;
    sentAt?: string;
  } | null;
}

interface ThreadMessage {
  id: string;
  type: 'sent' | 'received' | 'ai_response';
  subject: string;
  content: string;
  htmlContent: string;
  fromAddress?: string;
  toAddress?: string;
  stage?: string;
  sentAt?: string;
  receivedAt?: string;
  status?: string;
  responseType?: string;
  reasoning?: string;
  isReply?: boolean;
  conversationCount?: number;
  isThirdReply?: boolean;
  autoGenerated?: boolean;
}

export default function EmailResponsesNew() {
  const { t, currentLanguage } = useEmailResponseTranslations();
  const tf = (key: string, values?: Record<string, string | number>) => {
    let text = t(key);
    if (!values) return text;
    Object.entries(values).forEach(([name, value]) => {
      text = text.replace(`{${name}}`, String(value));
    });
    return text;
  };
  
  // State management
  const [emailData, setEmailData] = useState<CombinedEmailData[]>([]);
  const [selectedItem, setSelectedItem] = useState<CombinedEmailData | null>(null);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [sending, setSending] = useState(false);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [deletingEmailId, setDeletingEmailId] = useState<string | null>(null);
  const [showPreviewDialog, setShowPreviewDialog] = useState(false);
  const [threadMessages, setThreadMessages] = useState<ThreadMessage[]>([]);
  const [threadLoading, setThreadLoading] = useState(false);
  
  // Editing state
  const [editedSubject, setEditedSubject] = useState("");
  const [editedContent, setEditedContent] = useState("");
  const [isEditing, setIsEditing] = useState(false);

  // AI Settings state
  const [aiSettings, setAiSettings] = useState<any>(null);
  const [aiSettingsLoading, setAiSettingsLoading] = useState(false);
  const [aiSettingsSaving, setAiSettingsSaving] = useState(false);

  // Auto Reply toggle state
  const [autoReplyEnabled, setAutoReplyEnabled] = useState(false);
  const [autoReplyToggling, setAutoReplyToggling] = useState(false);

  // Credentials gating
  const [credsLoading, setCredsLoading] = useState(true);
  const [missingCreds, setMissingCreds] = useState<string[]>([]);
  // Required credentials — accept either legacy single-account fields OR
  // multi-account arrays (SMTP_ACCOUNTS / IMAP_ACCOUNTS / OPENAI_ACCOUNTS).
  const requiredCreds = [
    'IMAP_HOST','IMAP_PORT','IMAP_USER','IMAP_PASSWORD',
    'SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASSWORD',
    'OPENAI_API_KEY'
  ];

  // Check whether a credential group is satisfied, considering multi-account arrays.
  const hasImapConfigured = (creds: any): boolean => {
    if (creds.IMAP_HOST && creds.IMAP_PORT && creds.IMAP_USER && creds.IMAP_PASSWORD) return true;
    if (Array.isArray(creds.IMAP_ACCOUNTS) && creds.IMAP_ACCOUNTS.some((a: any) =>
      a?.IMAP_HOST && a?.IMAP_PORT && a?.IMAP_USER && a?.IMAP_PASSWORD
    )) return true;
    return false;
  };
  const hasSmtpConfigured = (creds: any): boolean => {
    if (creds.SMTP_HOST && creds.SMTP_PORT && creds.SMTP_USER && creds.SMTP_PASSWORD) return true;
    if (Array.isArray(creds.SMTP_ACCOUNTS) && creds.SMTP_ACCOUNTS.some((a: any) =>
      a?.SMTP_HOST && a?.SMTP_PORT && a?.SMTP_USER && a?.SMTP_PASSWORD
    )) return true;
    return false;
  };
  const hasOpenAiConfigured = (creds: any): boolean => {
    if (creds.OPENAI_API_KEY) return true;
    if (Array.isArray(creds.OPENAI_ACCOUNTS) && creds.OPENAI_ACCOUNTS.some((k: any) => typeof k === 'string' && k.trim())) return true;
    return false;
  };
  const computeMissingCreds = (creds: any): string[] => {
    const missing: string[] = [];
    if (!hasImapConfigured(creds)) missing.push('IMAP');
    if (!hasSmtpConfigured(creds)) missing.push('SMTP');
    if (!hasOpenAiConfigured(creds)) missing.push('OPENAI_API_KEY');
    return missing;
  };

  // Load AI settings
  const loadAiSettings = async () => {
    try {
      setAiSettingsLoading(true);
      const authHeader = auth.getAuthHeader();
      const res = await fetch('/api/email-responses/settings', {
        headers: authHeader ? { Authorization: authHeader } : undefined,
      });
      const data = await res.json();
      if (res.ok && data.success) {
        setAiSettings(data.settings);
        setAutoReplyEnabled(data.settings.autoReplyEnabled || false);
      } else {
        toast.error(tf('failedToLoadAiSettingsWithError', { error: data.error }));
      }
    } catch (error: any) {
      toast.error(tf('errorLoadingAiSettingsWithError', { error: error.message }));
    } finally {
      setAiSettingsLoading(false);
    }
  };

  // Save AI settings
  const saveAiSettings = async () => {
    try {
      setAiSettingsSaving(true);
      const authHeader = auth.getAuthHeader();
      const res = await fetch('/api/email-responses/settings', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {}),
        },
        body: JSON.stringify(aiSettings),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        toast.success(`✅ ${t('settingsSaved')}`);
        loadAiSettings(); // Reload
      } else {
        toast.error(tf('failedToSaveWithError', { error: data.error }));
      }
    } catch (error: any) {
      toast.error(tf('errorWithMessage', { error: error.message }));
    } finally {
      setAiSettingsSaving(false);
    }
  };

  // Load credentials
  useEffect(() => {
    (async () => {
      try {
        setCredsLoading(true);
        const authHeader = auth.getAuthHeader();
        const res = await fetch('/api/credentials', {
          headers: authHeader ? { Authorization: authHeader } : undefined,
        });
        const data = await res.json();
        if (res.ok && data.success) {
          const missing = computeMissingCreds(data.credentials || {});
          setMissingCreds(missing);
        } else {
          console.error('API Error:', data.error);
          toast.error(tf('failedToLoadCredentialsWithError', { error: data.error || t('unknownError') }));
          setMissingCreds(['IMAP','SMTP','OPENAI_API_KEY']);
        }
      } catch (error: any) {
        console.error('Error loading credentials:', error);
        toast.error(tf('failedToLoadCredentialsWithError', { error: error.message || t('networkError') }));
        setMissingCreds(['IMAP','SMTP','OPENAI_API_KEY']);
      } finally {
        setCredsLoading(false);
      }
    })();
  }, []);

  const credsOK = !credsLoading && missingCreds.length === 0;

  // Toggle Auto Reply
  const toggleAutoReply = async (enabled: boolean) => {
    try {
      setAutoReplyToggling(true);
      const authHeader = auth.getAuthHeader();
      const res = await fetch('/api/email-responses/settings', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {}),
        },
        body: JSON.stringify({ ...aiSettings, autoReplyEnabled: enabled }),
      });
      const data = await res.json();
      if (res.ok && data.success) {
        setAutoReplyEnabled(enabled);
        setAiSettings(data.settings);
        toast.success(enabled ? '✅ Auto Reply enabled — drafts will be sent automatically' : '⛔ Auto Reply disabled — manual review required');
      } else {
        toast.error(`Failed to toggle: ${data.error}`);
      }
    } catch (error: any) {
      toast.error(`Error: ${error.message}`);
    } finally {
      setAutoReplyToggling(false);
    }
  };

  // Load combined email data
  useEffect(() => {
    if (credsOK) {
      loadEmailData();
      loadAiSettings(); // Load AI settings too
    }
  }, [credsOK]);

  const loadEmailData = async () => {
    try {
      setLoading(true);
      const authHeader = auth.getAuthHeader();
      console.log('📧 Loading email data, authHeader present:', !!authHeader);

      const response = await fetch('/api/email-responses/combined', {
        headers: authHeader ? { Authorization: authHeader } : {}
      });
      const data = await response.json();

      console.log('📧 Combined API response:', { success: data.success, count: data.count, hasData: !!data.data });

      if (data.success) {
        setEmailData(data.data || []);
        console.log(`📧 Loaded ${data.count} emails with responses`);
      } else {
        console.error('API Error:', data.error);
        // Fallback: try the incoming API directly
        console.log('📧 Trying fallback: /api/email-responses/incoming');
        const fallbackRes = await fetch('/api/email-responses/incoming', {
          headers: authHeader ? { Authorization: authHeader } : {}
        });
        const fallbackData = await fallbackRes.json();
        if (fallbackData.success && fallbackData.emails?.length > 0) {
          // Convert incoming emails to combined format (no AI responses)
          const fallbackEmailData = fallbackData.emails.map((email: any) => ({
            email: {
              id: email.id,
              leadId: email.leadId || '',
              leadName: email.leadName,
              leadEmail: email.leadEmail,
              leadCompany: email.leadEmail?.split('@')[1] || 'Unknown',
              subject: email.subject,
              content: email.content,
              htmlContent: '',
              status: email.status,
              receivedAt: email.receivedAt,
              respondedAt: email.respondedAt,
              isReply: email.isReply || false,
              isRecent: true,
              threadId: email.threadId || '',
              sentiment: email.sentiment || 'neutral',
              conversationCount: email.conversationCount || 1,
              isThirdReply: email.isThirdReply || false,
              metadata: email.metadata || {}
            },
            aiResponse: null,
            hasResponse: false
          }));
          setEmailData(fallbackEmailData);
          console.log(`📧 Fallback: loaded ${fallbackEmailData.length} emails`);
        } else {
          toast.error(tf('failedToLoadEmailDataWithError', { error: data.error || t('unknownError') }));
        }
      }
    } catch (error: any) {
      console.error('Error loading email data:', error);
      toast.error(tf('failedToLoadEmailDataWithError', { error: error.message || t('networkError') }));
    } finally {
      setLoading(false);
    }
  };

  // Generate AI response for email without response
  const generateResponse = async (emailId: string) => {
    try {
      setGenerating(true);
      const loadingToast = toast.loading(`🤖 ${t('generatingAiResponseToast')}`);
      
      const authHeader = auth.getAuthHeader();
      const response = await fetch('/api/email-responses/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {})
        },
        body: JSON.stringify({ incomingEmailId: emailId })
      });

      const data = await response.json();
      
      // Dismiss loading toast
      toast.dismiss(loadingToast);
      
      if (data.success) {
        toast.success(`✅ ${t('responseGenerated')}`);
        loadEmailData(); // Reload to get the new response
      } else {
        toast.error(tf('failedWithError', { error: data.error }));
      }
    } catch (error: any) {
      toast.error(tf('errorWithMessage', { error: error.message }));
    } finally {
      setGenerating(false);
    }
  };

  // Send the AI response
  const sendResponse = async () => {
    if (!selectedItem?.aiResponse) return;
    
    try {
      setSending(true);
      const loadingToast = toast.loading(`📧 ${t('sendingEmailToast')}`);
      
      const authHeader = auth.getAuthHeader();
      const response = await fetch('/api/email-responses/send', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {})
        },
        body: JSON.stringify({
          responseId: selectedItem.aiResponse.id,
          customSubject: editedSubject || selectedItem.aiResponse.generatedSubject,
          customContent: editedContent || selectedItem.aiResponse.generatedContent
        })
      });

      const data = await response.json();
      
      // Dismiss loading toast
      toast.dismiss(loadingToast);
      
      if (data.success) {
        toast.success(`✅ ${t('responseSent')}`);
        setShowPreviewDialog(false);
        loadEmailData(); // Reload data
      } else {
        toast.error(tf('failedWithError', { error: data.error }));
      }
    } catch (error: any) {
      toast.error(tf('errorWithMessage', { error: error.message }));
    } finally {
      setSending(false);
    }
  };

  // Open preview dialog and load full conversation thread
  const openPreview = async (item: CombinedEmailData) => {
    setSelectedItem(item);
    setEditedSubject(item.aiResponse?.generatedSubject || '');
    setEditedContent(item.aiResponse?.generatedContent || '');
    setIsEditing(false);
    setShowPreviewDialog(true);
    setThreadMessages([]);
    setThreadLoading(true);

    // Load full conversation thread
    try {
      const authHeader = auth.getAuthHeader();
      const params = new URLSearchParams();
      if (item.email.leadId) params.set('leadId', item.email.leadId);
      else if (item.email.leadEmail) params.set('leadEmail', item.email.leadEmail);

      const res = await fetch(`/api/email-responses/thread?${params.toString()}`, {
        headers: authHeader ? { Authorization: authHeader } : {}
      });
      const data = await res.json();
      if (data.success && data.thread) {
        setThreadMessages(data.thread);
        console.log(`📧 Loaded ${data.thread.length} messages in thread`);
      }
    } catch (err: any) {
      console.error('Error loading thread:', err);
    } finally {
      setThreadLoading(false);
    }
  };

  // Save edited content without sending
  const saveEdits = async () => {
    if (!selectedItem?.aiResponse) return;
    
    try {
      setSaving(true);
      const loadingToast = toast.loading(`💾 ${t('savingChangesToast')}`);
      
      const authHeader = auth.getAuthHeader();
      const response = await fetch('/api/email-responses/update', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {}),
        },
        body: JSON.stringify({
          responseId: selectedItem.aiResponse.id,
          generatedSubject: editedSubject,
          generatedContent: editedContent
        })
      });

      const data = await response.json();
      
      // Dismiss loading toast
      toast.dismiss(loadingToast);
      
      if (data.success) {
        toast.success(`✅ ${t('changesSavedSuccessfully')}`);
        loadEmailData(); // Reload data
      } else {
        toast.error(tf('failedToSaveWithError', { error: data.error }));
      }
    } catch (error: any) {
      toast.error(tf('errorWithMessage', { error: error.message }));
    } finally {
      setSaving(false);
    }
  };

  // Direct send without opening dialog
  const directSend = async (item: CombinedEmailData) => {
    if (!item.aiResponse) return;
    
    try {
      setSending(true);
      const loadingToast = toast.loading(`📧 ${t('sendingEmailToast')}`);
      
      const authHeader = auth.getAuthHeader();
      const response = await fetch('/api/email-responses/send', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {}),
        },
        body: JSON.stringify({
          responseId: item.aiResponse.id,
          incomingEmailId: item.email.id
        })
      });

      const data = await response.json();
      
      // Dismiss loading toast
      toast.dismiss(loadingToast);
      
      if (data.success) {
        toast.success(`✅ ${t('responseSent')}`);
        loadEmailData(); // Reload data
      } else {
        toast.error(tf('failedWithError', { error: data.error }));
      }
    } catch (error: any) {
      toast.error(tf('errorWithMessage', { error: error.message }));
    } finally {
      setSending(false);
    }
  };

  // Refresh data
  const handleRefresh = () => {
    setRefreshing(true);
    loadEmailData().then(() => {
      setRefreshing(false);
      toast.success(`🔄 ${t('refreshed')}`);
    });
  };

  const deleteMessage = async (item: CombinedEmailData) => {
    const confirmed = confirm(t('deleteMessageConfirm'));
    if (!confirmed) return;

    try {
      setDeletingEmailId(item.email.id);
      const loadingToast = toast.loading(`🗑️ ${t('deletingMessageToast')}`);

      const authHeader = auth.getAuthHeader();
      const response = await fetch('/api/email-responses/delete', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...(authHeader ? { Authorization: authHeader } : {}),
        },
        body: JSON.stringify({ incomingEmailId: item.email.id })
      });

      const data = await response.json();
      toast.dismiss(loadingToast);

      if (data.success) {
        toast.success(`✅ ${t('messageDeletedSuccessfully')}`);
        if (selectedItem?.email.id === item.email.id) {
          setShowPreviewDialog(false);
          setSelectedItem(null);
        }
        await loadEmailData();
      } else {
        toast.error(tf('failedToDeleteWithError', { error: data.error || t('unknownError') }));
      }
    } catch (error: any) {
      toast.error(tf('errorDeletingMessageWithError', { error: error.message || t('unknownError') }));
    } finally {
      setDeletingEmailId(null);
    }
  };

  // Get status badge
  const getStatusBadge = (status: string) => {
    const variants = {
      'draft': 'bg-yellow-100 text-yellow-800',
      'sent': 'bg-green-100 text-green-800',
      'failed': 'bg-red-100 text-red-800',
      'pending_ai': 'bg-blue-100 text-blue-800',
      'unread': 'bg-orange-100 text-orange-800',
      'responded': 'bg-green-100 text-green-800'
    };
    return variants[status as keyof typeof variants] || 'bg-gray-100 text-gray-800';
  };

  // Filter emails by tab
  const filteredData = emailData.filter(item => {
    // Pending tab: has draft response
    // Sent tab: has sent response
    // All tab: everything
    return true; // We'll filter in TabsContent
  });

  const newEmailCount = emailData.filter(item => !item.aiResponse || item.email.status === 'unread').length;
  const pendingCount = emailData.filter(item => item.aiResponse?.status === 'draft').length;
  const sentCount = emailData.filter(item => item.aiResponse?.status === 'sent').length;
  const unreadCount = emailData.filter(item => item.email.status === 'unread').length;

  if (credsLoading) {
    return (
      <div className="flex items-center justify-center min-h-[40vh] text-zinc-400">
        <RefreshCw className="h-6 w-6 animate-spin mr-2" /> {t('loading')}
      </div>
    );
  }

  if (!credsOK) {
    return (
      <div className="space-y-8 p-6">
        <SectionHeader title={t('emailResponses')} description={t('manageEmailResponses')} />
        <Card className="border-red-300 bg-red-50">
          <CardHeader>
            <CardTitle className="text-red-700 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5" /> {t('missingCredentials')}
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm text-red-800">
            <p>{t('missingRequiredCredentials')}</p>
            <ul className="list-disc ml-6">
              {missingCreds.map((k) => (<li key={k}>{k}</li>))}
            </ul>
            <Button onClick={() => window.location.assign('/account-settings')}>
              {t('goToCredentials')}
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-8 p-6">
      {/* Header */}
      <div className="flex justify-between items-start">
        <SectionHeader
          title={`📧 ${t('emailResponseManager')}`}
          description={t('emailResponseManagerDescription')}
        />
        <div className="flex items-center gap-4">
          {/* Auto Reply Switch */}
          <div className="flex items-center gap-2 bg-zinc-900/50 border border-zinc-700 rounded-lg px-3 py-2">
            <span className="text-xs text-zinc-400 font-medium">Auto Reply</span>
            <Switch
              checked={autoReplyEnabled}
              onCheckedChange={toggleAutoReply}
              disabled={autoReplyToggling}
              className={cn(
                "data-[state=checked]:bg-green-600",
                "bg-gray-300"
              )}
            />
            <span className={cn("text-xs font-medium", autoReplyEnabled ? "text-green-400" : "text-zinc-500")}>
              {autoReplyEnabled ? "ON" : "OFF"}
            </span>
          </div>
          {/* Refresh Button */}
          <Button
            variant="outline"
            size="icon"
            onClick={handleRefresh}
            disabled={refreshing}
          >
            <RefreshCw className={`h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} />
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="bg-zinc-900/50 border-zinc-700">
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-zinc-400">{t('newEmailStat')}</p>
                <p className="text-2xl font-bold text-zinc-200">{newEmailCount}</p>
              </div>
              <Mail className="h-8 w-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-zinc-900/50 border-zinc-700">
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-zinc-400">{t('readyStat')}</p>
                <p className="text-2xl font-bold text-zinc-200">{pendingCount}</p>
              </div>
              <Bot className="h-8 w-8 text-purple-500" />
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-zinc-900/50 border-zinc-700">
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-zinc-400">{t('sentStat')}</p>
                <p className="text-2xl font-bold text-zinc-200">{sentCount}</p>
              </div>
              <CheckCircle className="h-8 w-8 text-green-500" />
            </div>
          </CardContent>
        </Card>
        
        <Card className="bg-zinc-900/50 border-zinc-700">
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-zinc-400">{t('allStat')}</p>
                <p className="text-2xl font-bold text-zinc-200">{emailData.length}</p>
              </div>
              <Mail className="h-8 w-8 text-zinc-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Main Content */}
      <Card className="bg-zinc-900/50 border-zinc-700">
        <CardContent className="p-6">
          <Tabs defaultValue="all">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="new">
                {t('newEmailStat')} ({newEmailCount})
              </TabsTrigger>
              <TabsTrigger value="ready">
                {t('readyStat')} ({pendingCount})
              </TabsTrigger>
              <TabsTrigger value="sent">
                {t('sentStat')} ({sentCount})
              </TabsTrigger>
              <TabsTrigger value="all">
                {t('allStat')} ({emailData.length})
              </TabsTrigger>
            </TabsList>

            {/* New Email Tab */}
            <TabsContent value="new" className="mt-6">
              {loading ? (
                <div className="flex items-center justify-center py-12">
                  <RefreshCw className="h-8 w-8 animate-spin text-zinc-400" />
                </div>
              ) : (
                <div className="space-y-4">
                  {emailData
                    .filter(item => !item.aiResponse || item.email.status === 'unread')
                    .map((item) => (
                      <EmailResponseCard
                        key={item.email.id}
                        item={item}
                        onView={openPreview}
                        onGenerate={generateResponse}
                        onDirectSend={directSend}
                        onDelete={deleteMessage}
                        deletingEmailId={deletingEmailId}
                        generating={generating}
                        sending={sending}
                      />
                    ))}
                  {emailData.filter(item => !item.aiResponse || item.email.status === 'unread').length === 0 && (
                    <div className="text-center py-12 text-zinc-400">
                      <CheckCircle className="h-12 w-12 mx-auto mb-3 opacity-50" />
                      <p>{t('noNewEmails')}</p>
                    </div>
                  )}
                </div>
              )}
            </TabsContent>

            {/* Ready to Send Tab */}
            <TabsContent value="ready" className="mt-6">
              {loading ? (
                <div className="flex items-center justify-center py-12">
                  <RefreshCw className="h-8 w-8 animate-spin text-zinc-400" />
                </div>
              ) : (
                <div className="space-y-4">
                  {emailData
                    .filter(item => item.aiResponse?.status === 'draft')
                    .map((item) => (
                      <EmailResponseCard
                        key={item.email.id}
                        item={item}
                        onView={openPreview}
                        onGenerate={generateResponse}
                        onDirectSend={directSend}
                        onDelete={deleteMessage}
                        deletingEmailId={deletingEmailId}
                        generating={generating}
                        sending={sending}
                      />
                    ))}
                  {emailData.filter(item => item.aiResponse?.status === 'draft').length === 0 && (
                    <div className="text-center py-12">
                      <CheckCircle className="h-16 w-16 text-zinc-400 mx-auto mb-4" />
                      <p className="text-zinc-400">{t('noEmailsReadyToSend')}</p>
                    </div>
                  )}
                </div>
              )}
            </TabsContent>

            {/* Sent Tab */}
            <TabsContent value="sent" className="mt-6">
              <div className="space-y-4">
                {emailData
                  .filter(item => item.aiResponse?.status === 'sent')
                  .map((item) => (
                    <EmailResponseCard
                      key={item.email.id}
                      item={item}
                      onView={openPreview}
                      onGenerate={generateResponse}
                      onDirectSend={directSend}
                      onDelete={deleteMessage}
                      deletingEmailId={deletingEmailId}
                      generating={generating}
                      sending={sending}
                    />
                  ))}
                {emailData.filter(item => item.aiResponse?.status === 'sent').length === 0 && (
                  <div className="text-center py-12">
                    <Mail className="h-16 w-16 text-zinc-400 mx-auto mb-4" />
                    <p className="text-zinc-400">{t('noSentEmails')}</p>
                  </div>
                )}
              </div>
            </TabsContent>

            {/* All Tab */}
            <TabsContent value="all" className="mt-6">
              <div className="space-y-4">
                {loading ? (
                  <div className="flex items-center justify-center py-12">
                    <RefreshCw className="h-8 w-8 animate-spin text-zinc-400" />
                  </div>
                ) : (
                  <>
                    {emailData.map((item) => (
                      <EmailResponseCard
                        key={item.email.id}
                        item={item}
                        onView={openPreview}
                        onGenerate={generateResponse}
                        onDirectSend={directSend}
                        onDelete={deleteMessage}
                        deletingEmailId={deletingEmailId}
                        generating={generating}
                        sending={sending}
                      />
                    ))}
                    {emailData.length === 0 && (
                      <div className="text-center py-12 text-zinc-400">
                        <Mail className="h-12 w-12 mx-auto mb-3 opacity-50" />
                        <p>No emails found. Replies will appear here when leads respond to your outreach.</p>
                      </div>
                    )}
                  </>
                )}
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* AI Settings Section - Separate card below */}
      <Card className="bg-zinc-900/50 border-zinc-700">
        <CardHeader>
          <CardTitle className="text-zinc-200 flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-purple-400" />
            {t('aiSettings')}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="mt-6">
              {aiSettingsLoading ? (
                <div className="flex items-center justify-center py-12">
                  <RefreshCw className="h-8 w-8 animate-spin text-zinc-400" />
                </div>
              ) : aiSettings ? (
                <div className="space-y-6">
                  <div className="bg-zinc-800/30 rounded-lg p-4 border border-zinc-700">
                    <h3 className="text-lg font-semibold text-zinc-200 mb-2 flex items-center gap-2">
                      <Sparkles className="h-5 w-5 text-purple-400" />
                      {t('aiResponseConfiguration')}
                    </h3>
                    <p className="text-sm text-zinc-400">
                      {t('aiResponseConfigurationDescription')}
                    </p>
                  </div>

                  {/* Company Information */}
                  <Card className="bg-zinc-800/50 border-zinc-700">
                    <CardHeader>
                      <CardTitle className="text-zinc-200 flex items-center gap-2">
                        <Building className="h-5 w-5" />
                        {t('companyInformation')}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <Label className="text-zinc-300">{t('companyName')}</Label>
                          <Input
                            value={aiSettings.companyName || ''}
                            onChange={(e) => setAiSettings({ ...aiSettings, companyName: e.target.value })}
                            className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1"
                            placeholder="QuasarSEO"
                          />
                        </div>
                        <div>
                          <Label className="text-zinc-300">{t('senderName')}</Label>
                          <Input
                            value={aiSettings.senderName || ''}
                            onChange={(e) => setAiSettings({ ...aiSettings, senderName: e.target.value })}
                            className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1"
                            placeholder="Team QuasarSEO"
                          />
                        </div>
                      </div>
                      <div>
                        <Label className="text-zinc-300">{t('senderEmail')}</Label>
                        <Input
                          type="email"
                          value={aiSettings.senderEmail || ''}
                          onChange={(e) => setAiSettings({ ...aiSettings, senderEmail: e.target.value })}
                          className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1"
                          placeholder="info@quasarseo.nl"
                        />
                      </div>
                      <div>
                        <Label className="text-zinc-300">{t('emailSignature')}</Label>
                        <Textarea
                          value={aiSettings.signature || ''}
                          onChange={(e) => setAiSettings({ ...aiSettings, signature: e.target.value })}
                          className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1 min-h-[80px]"
                          placeholder={t('emailSignaturePlaceholder')}
                        />
                        <p className="text-xs text-zinc-400 mt-1">
                          {t('signatureAppendedDescription')}
                        </p>
                      </div>
                    </CardContent>
                  </Card>

                  {/* AI Behavior Settings */}
                  <Card className="bg-zinc-800/50 border-zinc-700">
                    <CardHeader>
                      <CardTitle className="text-zinc-200 flex items-center gap-2">
                        <Bot className="h-5 w-5" />
                        {t('aiBehaviorSettings')}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <div>
                          <Label className="text-zinc-300">{t('tone')}</Label>
                          <select
                            value={aiSettings.defaultTone || 'professional'}
                            onChange={(e) => setAiSettings({ ...aiSettings, defaultTone: e.target.value })}
                            className="w-full mt-1 bg-zinc-900 border border-zinc-600 text-zinc-200 rounded-md px-3 py-2"
                          >
                            <option value="professional">{t('professional')}</option>
                            <option value="friendly">{t('friendly')}</option>
                            <option value="casual">{t('casual')}</option>
                            <option value="formal">{t('formal')}</option>
                          </select>
                        </div>
                        <div>
                          <Label className="text-zinc-300">{t('maxResponseLengthWords')}</Label>
                          <Input
                            type="number"
                            min="50"
                            max="1000"
                            value={aiSettings.maxResponseLength || 300}
                            onChange={(e) => setAiSettings({ ...aiSettings, maxResponseLength: parseInt(e.target.value) || 300 })}
                            className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1"
                          />
                        </div>
                        <div>
                          <Label className="text-zinc-300">{t('autoSendThresholdPercent')}</Label>
                          <Input
                            type="number"
                            min="0"
                            max="100"
                            value={aiSettings.autoSendThreshold || 85}
                            onChange={(e) => setAiSettings({ ...aiSettings, autoSendThreshold: parseInt(e.target.value) || 85 })}
                            className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1"
                            disabled
                          />
                          <p className="text-xs text-zinc-400 mt-1">
                            🔒 {t('autoSendDisabledDrafts')}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={aiSettings.isEnabled !== false}
                          onChange={(e) => setAiSettings({ ...aiSettings, isEnabled: e.target.checked })}
                          className="h-4 w-4 rounded border-zinc-600 bg-zinc-900 text-purple-500"
                        />
                        <Label className="text-zinc-300 cursor-pointer">
                          {t('enableAiResponseGeneration')}
                        </Label>
                      </div>
                      <div className="flex items-center gap-2">
                        <input
                          type="checkbox"
                          checked={aiSettings.includeCompanyInfo !== false}
                          onChange={(e) => setAiSettings({ ...aiSettings, includeCompanyInfo: e.target.checked })}
                          className="h-4 w-4 rounded border-zinc-600 bg-zinc-900 text-purple-500"
                        />
                        <Label className="text-zinc-300 cursor-pointer">
                          {t('includeCompanyInfoInResponses')}
                        </Label>
                      </div>
                    </CardContent>
                  </Card>

                  {/* AI Prompt Configuration */}
                  <Card className="bg-zinc-800/50 border-zinc-700">
                    <CardHeader>
                      <CardTitle className="text-zinc-200 flex items-center gap-2">
                        <MessageSquare className="h-5 w-5" />
                        {t('aiPromptConfiguration')}
                      </CardTitle>
                    </CardHeader>
                    <CardContent className="space-y-4">
                      <div>
                        <Label className="text-zinc-300">{t('responsePromptTemplate')}</Label>
                        <Textarea
                          value={aiSettings.responsePrompt || ''}
                          onChange={(e) => setAiSettings({ ...aiSettings, responsePrompt: e.target.value })}
                          className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1 min-h-[300px] font-mono text-sm"
                          placeholder={t('responsePromptTemplatePlaceholder')}
                        />
                        <p className="text-xs text-zinc-400 mt-1">
                          {t('responsePromptTemplateDescription')}
                        </p>
                      </div>
                      <div>
                        <Label className="text-zinc-300">{t('customInstructionsOptional')}</Label>
                        <Textarea
                          value={aiSettings.customInstructions || ''}
                          onChange={(e) => setAiSettings({ ...aiSettings, customInstructions: e.target.value })}
                          className="bg-zinc-900 border-zinc-600 text-zinc-200 mt-1 min-h-[100px]"
                          placeholder={t('customInstructionsOptionalPlaceholder')}
                        />
                        <p className="text-xs text-zinc-400 mt-1">
                          {t('customInstructionsOptionalDescription')}
                        </p>
                      </div>
                    </CardContent>
                  </Card>

                  {/* Save Button */}
                  <div className="flex justify-end">
                    <Button
                      onClick={saveAiSettings}
                      disabled={aiSettingsSaving}
                      className="bg-purple-600 hover:bg-purple-700 text-white"
                    >
                      {aiSettingsSaving ? (
                        <>
                          <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                          {t('saving')}
                        </>
                      ) : (
                        <>
                          <CheckCircle className="h-4 w-4 mr-2" />
                          {t('saveAiSettings')}
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              ) : (
                <div className="text-center py-12 text-zinc-400">
                  <p>{t('failedToLoadSettings')}</p>
                  <Button onClick={loadAiSettings} variant="outline" className="mt-4">
                    <RefreshCw className="h-4 w-4 mr-2" />
                    {t('retry')}
                  </Button>
                </div>
              )}
          </div>
        </CardContent>
      </Card>

      {/* Preview/Send Dialog - Conversation Thread View */}
      <Dialog open={showPreviewDialog} onOpenChange={setShowPreviewDialog}>
        <DialogContent className="!w-[90vw] !h-[95vh] !max-w-[90vw] !max-h-[95vh] bg-zinc-900 border-zinc-700 flex flex-col p-0" style={{ width: '90vw', height: '95vh', maxWidth: '90vw', maxHeight: '95vh' }}>
          <DialogHeader className="px-6 py-4 border-b border-zinc-700 flex-shrink-0">
            <DialogTitle className="text-zinc-200 flex items-center gap-2">
              <Mail className="h-5 w-5" />
              Conversation with {selectedItem?.email.leadName || 'Lead'}
            </DialogTitle>
            <DialogDescription className="text-zinc-400">
              {selectedItem?.email.leadEmail} — Full conversation thread
            </DialogDescription>
          </DialogHeader>

          {selectedItem && (
            <div className="flex-1 overflow-hidden flex flex-col">
              {/* Conversation Thread — scrollable */}
              <div className="flex-1 overflow-y-auto px-6 py-4 space-y-3">
                {threadLoading ? (
                  <div className="flex items-center justify-center py-12">
                    <RefreshCw className="h-8 w-8 animate-spin text-zinc-400" />
                  </div>
                ) : threadMessages.length > 0 ? (
                  <>
                    {/* Render full conversation thread from API */}
                    {threadMessages.map((msg, idx) => (
                      <ConversationMessage key={msg.id + idx} msg={msg} leadName={selectedItem.email.leadName} currentLanguage={currentLanguage} />
                    ))}
                  </>
                ) : (
                  <>
                    {/* Fallback: show from combined data if thread API didn't return results */}
                    {/* Original sent email */}
                    {selectedItem.originalSentEmail && (
                      <ConversationMessage
                        msg={{
                          id: 'original-sent',
                          type: 'sent',
                          subject: selectedItem.originalSentEmail.subject,
                          content: selectedItem.originalSentEmail.content,
                          htmlContent: selectedItem.originalSentEmail.htmlContent,
                          fromAddress: selectedItem.originalSentEmail.fromAddress,
                          sentAt: selectedItem.originalSentEmail.sentAt,
                          stage: selectedItem.originalSentEmail.stage,
                        }}
                        leadName={selectedItem.email.leadName}
                        currentLanguage={currentLanguage}
                      />
                    )}
                    {/* Incoming reply */}
                    <ConversationMessage
                      msg={{
                        id: selectedItem.email.id,
                        type: 'received',
                        subject: selectedItem.email.subject,
                        content: selectedItem.email.content,
                        htmlContent: selectedItem.email.htmlContent || '',
                        receivedAt: selectedItem.email.receivedAt,
                        isReply: selectedItem.email.isReply,
                        conversationCount: selectedItem.email.conversationCount,
                        isThirdReply: selectedItem.email.isThirdReply,
                      }}
                      leadName={selectedItem.email.leadName}
                      currentLanguage={currentLanguage}
                    />
                    {/* AI response */}
                    {selectedItem.aiResponse && (
                      <ConversationMessage
                        msg={{
                          id: selectedItem.aiResponse.id,
                          type: 'ai_response',
                          subject: selectedItem.aiResponse.generatedSubject,
                          content: selectedItem.aiResponse.generatedContent,
                          htmlContent: selectedItem.aiResponse.generatedContent,
                          status: selectedItem.aiResponse.status,
                          responseType: selectedItem.aiResponse.responseType,
                          reasoning: selectedItem.aiResponse.reasoning,
                          sentAt: selectedItem.aiResponse.sentAt || selectedItem.aiResponse.createdAt,
                        }}
                        leadName={selectedItem.email.leadName}
                        currentLanguage={currentLanguage}
                      />
                    )}
                  </>
                )}
              </div>

              {/* AI Response Editor — only show when there's a draft to edit */}
              {selectedItem.aiResponse && selectedItem.aiResponse.status === 'draft' && (
                <div className="border-t border-zinc-700 px-6 py-4 flex-shrink-0 bg-zinc-800/50">
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <Bot className="h-4 w-4 text-purple-400" />
                      <span className="text-sm font-medium text-zinc-200">AI Response Draft</span>
                      <Badge className="bg-yellow-100 text-yellow-800 text-xs">{t('draft')}</Badge>
                    </div>
                    <div className="flex items-center gap-2">
                      {!isEditing && (
                        <Button
                          size="sm"
                          onClick={saveEdits}
                          disabled={saving}
                          className="bg-green-600 hover:bg-green-700 text-white font-semibold"
                        >
                          {saving ? <RefreshCw className="h-4 w-4 mr-2 animate-spin" /> : <Save className="h-4 w-4 mr-2" />}
                          {saving ? t('saving') : t('save')}
                        </Button>
                      )}
                      <Button
                        size="sm"
                        onClick={() => setIsEditing(!isEditing)}
                        className="bg-purple-600 hover:bg-purple-700 text-white font-semibold"
                      >
                        <Edit className="h-4 w-4 mr-2" />
                        {isEditing ? t('preview') : t('edit')}
                      </Button>
                    </div>
                  </div>

                  {isEditing ? (
                    <div className="space-y-3">
                      <Input
                        value={editedSubject}
                        onChange={(e) => setEditedSubject(e.target.value)}
                        className="w-full text-sm text-gray-900 bg-white border border-zinc-600 rounded-lg px-3 py-2"
                        placeholder="Subject"
                      />
                      <Textarea
                        value={editedContent}
                        onChange={(e) => setEditedContent(e.target.value)}
                        className="w-full min-h-[150px] text-sm text-gray-900 bg-white border border-zinc-600 rounded-lg px-3 py-2 font-mono resize-none"
                        placeholder="Email content (HTML)"
                      />
                    </div>
                  ) : (
                    <div className="bg-white rounded-lg p-4 max-h-[200px] overflow-y-auto">
                      <div
                        className="text-sm text-gray-900 gmail-content leading-relaxed"
                        dangerouslySetInnerHTML={{ __html: editedContent || selectedItem.aiResponse.generatedContent }}
                      />
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          <DialogFooter className="px-6 py-4 border-t border-zinc-700 flex-shrink-0">
            <Button
              variant="outline"
              onClick={() => setShowPreviewDialog(false)}
              className="mr-2"
            >
              {t('close')}
            </Button>
            {selectedItem?.aiResponse?.status === 'draft' && (
              <Button
                onClick={sendResponse}
                disabled={sending}
                className="bg-green-600 hover:bg-green-700 text-white"
              >
                {sending ? (
                  <>
                    <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    {t('sending')}
                  </>
                ) : (
                  <>
                    <Send className="h-4 w-4 mr-2" />
                    {t('sendEmail')}
                  </>
                )}
              </Button>
            )}
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// Conversation Message Component — renders a single message in the thread
function ConversationMessage({ msg, leadName, currentLanguage }: { msg: ThreadMessage; leadName: string; currentLanguage: string }) {
  const isSent = msg.type === 'sent';
  const isReceived = msg.type === 'received';
  const isAI = msg.type === 'ai_response';

  const dateStr = msg.sentAt || msg.receivedAt || '';
  const formattedDate = dateStr ? new Date(dateStr).toLocaleString(currentLanguage === 'nl' ? 'nl-NL' : 'en-US', {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
    hour12: true
  }) : '';

  // Strip quoted text from received emails for cleaner display
  const renderContent = (content: string, htmlContent?: string) => {
    if (htmlContent && htmlContent.trim()) {
      return <div className="gmail-content leading-relaxed" dangerouslySetInnerHTML={{ __html: htmlContent }} />;
    }
    if (!content) return <p className="text-gray-400 italic">(no content)</p>;

    // For received emails, try to separate the reply from quoted original
    if (isReceived) {
      const hasQuoted = content.includes('\n>') || content.includes('wrote:');
      if (hasQuoted) {
        const parts = content.split(/(?=On .+? wrote:)/);
        return (
          <>
            {parts[0] && parts[0].trim() && (
              <p className="whitespace-pre-wrap text-gray-900">{parts[0].trim()}</p>
            )}
            {parts[1] && (
              <div className="mt-3 pt-3 border-t border-gray-200">
                <p className="text-xs text-gray-500 mb-1">--- Quoted original ---</p>
                <div className="text-gray-500 text-sm space-y-1">
                  {parts[1].split('\n').filter(l => l.trim()).map((line, i) => (
                    <p key={i} className="leading-relaxed">{line.replace(/^>\s*/, '')}</p>
                  ))}
                </div>
              </div>
            )}
          </>
        );
      }
    }
    return <p className="whitespace-pre-wrap text-gray-900">{content}</p>;
  };

  // Sent email (what we sent to the lead)
  if (isSent) {
    return (
      <div className="flex justify-end">
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 max-w-[80%] w-full">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-full bg-blue-500 flex items-center justify-center text-white text-sm font-semibold">
              You
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <span className="text-sm font-medium text-gray-900">You (sent)</span>
                {msg.stage && (
                  <Badge className="bg-blue-100 text-blue-700 text-xs">{msg.stage}</Badge>
                )}
              </div>
              <div className="text-xs text-gray-500">
                To: {leadName} · {formattedDate}
              </div>
            </div>
          </div>
          <p className="text-sm font-medium text-gray-700 mb-2">{msg.subject}</p>
          <div className="text-sm text-gray-800 bg-white rounded p-3 max-h-[300px] overflow-y-auto">
            {renderContent(msg.content, msg.htmlContent)}
          </div>
        </div>
      </div>
    );
  }

  // Received email (lead's reply)
  if (isReceived) {
    const statusColors: Record<string, string> = {
      unread: 'bg-orange-100 text-orange-700',
      pending_ai: 'bg-blue-100 text-blue-700',
      processed: 'bg-gray-100 text-gray-600',
      responded: 'bg-green-100 text-green-700',
    };
    return (
      <div className="flex justify-start">
        <div className="bg-green-50 border border-green-200 rounded-lg p-4 max-w-[80%] w-full">
          <div className="flex items-center gap-2 mb-2">
            <div className="w-8 h-8 rounded-full bg-green-500 flex items-center justify-center text-white text-sm font-semibold">
              {leadName.charAt(0).toUpperCase()}
            </div>
            <div className="flex-1">
              <div className="flex items-center gap-2">
                <span className="text-sm font-medium text-gray-900">{leadName} (reply)</span>
                {msg.isThirdReply && (
                  <Badge className="bg-orange-100 text-orange-700 text-xs">3rd+ reply</Badge>
                )}
                {msg.conversationCount && msg.conversationCount > 1 && (
                  <Badge className="bg-purple-100 text-purple-700 text-xs">#{msg.conversationCount}</Badge>
                )}
                {msg.status && (
                  <Badge className={statusColors[msg.status] || 'bg-gray-100 text-gray-600'}>{msg.status}</Badge>
                )}
              </div>
              <div className="text-xs text-gray-500">
                From: {msg.fromAddress || leadName} · {formattedDate}
              </div>
            </div>
          </div>
          <p className="text-sm font-medium text-gray-700 mb-2">{msg.subject}</p>
          <div className="text-sm text-gray-800 bg-white rounded p-3 max-h-[300px] overflow-y-auto">
            {renderContent(msg.content, msg.htmlContent)}
          </div>
        </div>
      </div>
    );
  }

  // AI response (what we generated/sent back)
  const aiStatusColors: Record<string, string> = {
    draft: 'bg-yellow-100 text-yellow-700',
    sent: 'bg-green-100 text-green-700',
    failed: 'bg-red-100 text-red-700',
  };
  return (
    <div className="flex justify-end">
      <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 max-w-[80%] w-full">
        <div className="flex items-center gap-2 mb-2">
          <div className="w-8 h-8 rounded-full bg-purple-500 flex items-center justify-center text-white text-sm font-semibold">
            <Bot className="h-4 w-4" />
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <span className="text-sm font-medium text-gray-900">AI Response ({msg.responseType || 'generated'})</span>
              {msg.status && (
                <Badge className={aiStatusColors[msg.status] || 'bg-gray-100 text-gray-600'}>{msg.status}</Badge>
              )}
              {msg.autoGenerated && (
                <Badge className="bg-zinc-200 text-zinc-600 text-xs">auto</Badge>
              )}
            </div>
            <div className="text-xs text-gray-500">
              To: {leadName} · {formattedDate}
            </div>
          </div>
        </div>
        <p className="text-sm font-medium text-gray-700 mb-2">{msg.subject}</p>
        <div className="text-sm text-gray-800 bg-white rounded p-3 max-h-[300px] overflow-y-auto">
          {renderContent(msg.content, msg.htmlContent)}
        </div>
        {msg.reasoning && (
          <div className="mt-2 text-xs text-purple-600 bg-purple-100/50 rounded px-2 py-1">
            <Bot className="h-3 w-3 inline mr-1" />
            {msg.reasoning}
          </div>
        )}
      </div>
    </div>
  );
}

// Email Response Card Component
function EmailResponseCard({ 
  item, 
  onView, 
  onGenerate,
  onDirectSend,
  onDelete,
  deletingEmailId,
  generating,
  sending 
}: { 
  item: CombinedEmailData; 
  onView: (item: CombinedEmailData) => void;
  onGenerate: (emailId: string) => void;
  onDirectSend: (item: CombinedEmailData) => void;
  onDelete: (item: CombinedEmailData) => void;
  deletingEmailId: string | null;
  generating: boolean;
  sending: boolean;
}) {
  const { t, currentLanguage } = useEmailResponseTranslations();
  const isDeleting = deletingEmailId === item.email.id;
  const emailStatusLabels: Record<string, string> = {
    unread: t('unread'),
    responded: t('responded'),
    pending_ai: t('pendingAI'),
  };
  const aiStatusLabels: Record<string, string> = {
    draft: t('draft'),
    sent: t('sentStat'),
    failed: t('failed'),
  };

  const getStatusBadge = (status: string) => {
    const variants = {
      'draft': 'bg-yellow-100 text-yellow-800',
      'sent': 'bg-green-100 text-green-800',
      'failed': 'bg-red-100 text-red-800',
      'pending_ai': 'bg-blue-100 text-blue-800',
      'unread': 'bg-orange-100 text-orange-800'
    };
    return variants[status as keyof typeof variants] || 'bg-gray-100 text-gray-800';
  };

  return (
    <Card className="bg-zinc-800/50 border-zinc-600 hover:bg-zinc-800/70 transition-colors">
      <CardContent className="p-4">
        <div className="flex items-start justify-between gap-4">
          {/* Left: Email Info */}
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-2 flex-wrap">
              <h3 className="font-medium text-zinc-200 truncate">
                {item.email.leadName} ({item.email.leadCompany})
              </h3>
              <Badge className={getStatusBadge(item.email.status)}>
                {emailStatusLabels[item.email.status] || item.email.status}
              </Badge>
              {item.aiResponse && (
                <Badge className={getStatusBadge(item.aiResponse.status)}>
                  <Bot className="h-3 w-3 mr-1" />
                  {aiStatusLabels[item.aiResponse.status] || item.aiResponse.status}
                </Badge>
              )}
              {item.email.isThirdReply && (
                <Badge className="bg-orange-600 text-white">
                  🇳🇱 {t('dutchTemplate')}
                </Badge>
              )}
              {item.totalSentEmails > 0 && (
                <Badge className="bg-zinc-600 text-zinc-200 text-xs">
                  {item.totalSentEmails} sent
                </Badge>
              )}
            </div>

            {/* Incoming Reply Section */}
            <div className="bg-green-900/20 border border-green-700/30 rounded p-2 mb-2">
              <p className="text-xs text-green-400 font-medium mb-1 flex items-center gap-1">
                <Mail className="h-3 w-3" />
                Reply from {item.email.leadName}:
              </p>
              <p className="text-sm text-zinc-300 font-medium mb-1 truncate">
                {item.email.subject}
              </p>
              <p className="text-xs text-zinc-400 line-clamp-2">
                {item.email.content?.substring(0, 200)}
              </p>
            </div>

            {/* AI Response Section */}
            {item.aiResponse && (
              <div className="bg-purple-900/20 border border-purple-700/30 rounded p-2">
                <p className="text-xs text-purple-400 font-medium mb-1 flex items-center gap-1">
                  <Bot className="h-3 w-3" />
                  {item.aiResponse.status === 'sent' ? 'Sent reply:' : item.aiResponse.status === 'draft' ? 'Draft reply:' : 'Failed reply:'}
                </p>
                <p className="text-xs text-zinc-300 font-medium mb-1 truncate">
                  {item.aiResponse.generatedSubject}
                </p>
                <p className="text-xs text-zinc-500 line-clamp-2">
                  {item.aiResponse.generatedContent?.replace(/<[^>]*>/g, '').substring(0, 200)}
                </p>
              </div>
            )}

            <div className="flex items-center gap-4 mt-2 text-xs text-zinc-500">
              <span className="flex items-center gap-1">
                <Clock className="h-3 w-3" />
                {new Date(item.email.receivedAt).toLocaleDateString(currentLanguage === 'nl' ? 'nl-NL' : 'en-US')}
              </span>
              <span>{item.email.leadEmail}</span>
            </div>
          </div>

          {/* Right: Actions */}
          <div className="flex flex-col gap-2">
            {item.aiResponse ? (
              <>
                {item.aiResponse.status === 'draft' ? (
                  <>
                    {/* Review Button - Opens popup */}
                    <Button
                      size="sm"
                      onClick={() => onView(item)}
                      variant="outline"
                      className="border-blue-600 text-blue-600 hover:bg-blue-50"
                    >
                      <Eye className="h-4 w-4 mr-1" />
                      {t('review')}
                    </Button>

                    {/* Send Button - Direct send with loader */}
                    <Button
                      size="sm"
                      onClick={() => onDirectSend(item)}
                      disabled={sending}
                      className="bg-green-600 hover:bg-green-700 text-white"
                    >
                      {sending ? (
                        <RefreshCw className="h-4 w-4 mr-1 animate-spin" />
                      ) : (
                        <Send className="h-4 w-4 mr-1" />
                      )}
                      {sending ? t('sending') : t('send')}
                    </Button>
                  </>
                ) : (
                  <Button
                    size="sm"
                    onClick={() => onView(item)}
                    className="bg-blue-600 hover:bg-blue-700 text-white"
                  >
                    <Eye className="h-4 w-4 mr-1" />
                    {t('view')}
                  </Button>
                )}
              </>
            ) : (
              <Button
                size="sm"
                onClick={() => onGenerate(item.email.id)}
                disabled={generating}
                className="bg-purple-600 hover:bg-purple-700 text-white"
              >
                {generating ? (
                  <RefreshCw className="h-4 w-4 animate-spin" />
                ) : (
                  <>
                    <Bot className="h-4 w-4 mr-1" />
                    {t('generate')}
                  </>
                )}
              </Button>
            )}

            <Button
              size="sm"
              variant="outline"
              onClick={() => onDelete(item)}
              disabled={isDeleting}
              className="border-red-600 text-red-600 hover:bg-red-50"
            >
              {isDeleting ? (
                <RefreshCw className="h-4 w-4 mr-1 animate-spin" />
              ) : (
                <Trash2 className="h-4 w-4 mr-1" />
              )}
              {isDeleting ? t('deleting') : t('delete')}
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
